src/objects/CBS_Hangar__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Values_Set</valueSetName>
        </valueSet>
    </fields>
    <label>Hangar</label>
    <nameField>
        <label>Hangar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hangars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country_Values_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <customValue>
        <fullName>Ukraine</fullName>
    </customValue>
    <masterLabel>Country Values Set</masterLabel>
</GlobalValueSet>

src/classes/CBS_HangarController.cls
public with sharing class CBS_HangarController {
    @AuraEnabled
    public static List<CBS_Hangar__c> searchHangars(CBS_Hangar__c searchedHangar) {
        String nameParam, emailParam, cityParam;
        String query = 'SELECT Id, Name, Country__c, City__c FROM CBS_Hangar__c WHERE Country__c = \'' + searchedHangar.Country__c + '\'';

        if (String.isNotEmpty(searchedHangar.Name)) {
            nameParam = ' \'%' + searchedHangar.Name + '%\' ';
            query += ' AND Name LIKE ' + nameParam;
        }

        if (String.isNotEmpty(searchedHangar.City__c)) {
            cityParam = ' \'%' + searchedHangar.City__c + '%\' ';
            query += ' AND Name LIKE ' + cityParam;
        }

        System.debug('QUERY: ' + query);

        System.debug(Database.query(query));
        return Database.query(query);
    }
}